### PR TITLE
add and compile for arm64e with latest changes

### PR DESCRIPTION
**Pull request by kasiimh1**
linked the deb too so you can submit it!

### CODE REVIEW

**Comment by Wh0ba** [comment]
Thank you 
I compile on iOS so I can’t really compile for arm64e 
That’s why I didn’t add it as a target architecture 
But I’ll submit the one you compiled to the bigboss and my repo 
Thanks again

**Comment by Wh0ba** [comment]
Sorry to ask 
But can you compile it with the latest change ?
I had to move the icon from /var/mobile/ to /Library/ bc th bigboss repo said it should go there although there is no difference

**Comment by kasiimh1** [comment]
Compiled per your request with latest changes 

/packages contains latest deb for you to submit

fixed the code merge issue so now you can accept the PR if you want

**Comment by Wh0ba** [comment]
you didn't update the layout folder 
now the icon doesn't show up 
make sure to pull the latest changes including the change to the layout folder

**Comment by kasiimh1** [comment]
Should now be fixed! Deb is recompiled.

**Comment by Wh0ba** [comment]
Thanks I’ve updated it 
I’ve submitted it to the bigboss repo

**Pull request merged**
